package com.example.demo.Enum;

public enum OrderStatus {

    AGUARDANDO_AUTORIZACAO_A1,
    AGUARDANDO_AUTORIZACAO_A2,
    AGUARDANDO_AUTORIZACAO_A3,
    AUTORIZADO_AGUARDANDO_COMPRA,
    COMPRADO_AGUARDANDO_RETIRADA,
    ORDEM_FINALIZADA

}
